### ISSUE TITLE
询问

### ISSUE THREAD

**Issue by lmq-97** [sz-sdr/SDR-LIBRARY#1]
我想问一下，你的这个com.github.HyfSunshine:SdrBaseLibrary:0.7.1库还存在吗？或者有没有备份，因为现在找不到了

**Comment by HyFun** [comment]
SdrBaseLibrary这个库很久之前的了，我已经删除了，现在用的都是这个

**Comment by lmq-97** [comment]
我现在有个问题HikVideoPlayer.jar
这个包，海康那边的数据流地址已经获取到了
给播放器不能播放，这个包是从哪里来的





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "sz-sdr/SDR-LIBRARY"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月26日(星期三) 上午10:43
收件人:&nbsp;"sz-sdr/SDR-LIBRARY"<SDR-LIBRARY@noreply.github.com&gt;;
抄送:&nbsp;"&amp;%千里寻欢；#@￥"<1614947334@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [sz-sdr/SDR-LIBRARY] 询问 (#1)





 
SdrBaseLibrary这个库很久之前的了，我已经删除了，现在用的都是这个

**Comment by HyFun** [comment]
> 我现在有个问题HikVideoPlayer.jar 这个包，海康那边的数据流地址已经获取到了 给播放器不能播放，这个包是从哪里来的
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "sz-sdr/SDR-LIBRARY" <notifications@github.com&gt;; 发送时间:&nbsp;2020年8月26日(星期三) 上午10:43 收件人:&nbsp;"sz-sdr/SDR-LIBRARY"<SDR-LIBRARY@noreply.github.com&gt;; 抄送:&nbsp;"&amp;%千里寻欢；#@￥"<1614947334@qq.com&gt;;"Author"<author@noreply.github.com&gt;; 主题:&nbsp;Re: [sz-sdr/SDR-LIBRARY] 询问 (#1) SdrBaseLibrary这个库很久之前的了，我已经删除了，现在用的都是这个 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

对应海康ISC平台视频SDK-android 版本的库
https://open.hikvision.com/download/5c67f1e2f05948198c909700?type=10
